### ISSUE TITLE
Types keyword broken when reading

### ISSUE THREAD

**Issue by JockLawrie** [cjprybol/uCSV.jl#12]
Seems types are no longer detected when reading data?

```julia
using DataFrames
using Dates
using uCSV

# Create data and write to disk
data = DataFrame(dt=[Date(2018,10,8)])
uCSV.write("test.tsv", data; header=String.(names(data)), delim='\t')

# Read data from disk
tp = Dict("dt" => Date)
data2 = DataFrame(uCSV.read("test.tsv"; delim='\t', header=1, types=tp))
eltype(data2[:dt]) == Date  # False. Should be true.
```

**Comment by cjprybol** [comment]
Thanks for the report, I was able to replicate the issue. One of the deprecation fixes from the last update was incorrect and column names weren't being matched correctly when reading. I added your example as a test case so it shouldn't happen again. Once https://github.com/cjprybol/uCSV.jl/pull/13 passes CI I'll merge the fix into master and tag a new release

**Comment by JockLawrie** [comment]
Great, thanks again!

**Comment by cjprybol** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/18722
