### ISSUE TITLE
Cannot write DataFrame when using DataFrames 0.15.2

### ISSUE THREAD

**Issue by JockLawrie** [cjprybol/uCSV.jl#15]
Hi there,

I just upgraded from DataFrames 0.14.1 to DataFrames 0.15.2.
I can no longer write a simple `DataFrame` to a file with `uCSV`.
Here's a minimal working example:

```julia
using uCSV
using DataFrames

tbl = DataFrame(
    patientid = [1, 2, 3, 4],
    age       = [11, 22, 33, 444],
    dose      = ["small", "medium", "large", "medium"],
    fever     = [false, true, true, false]
)
filename = "/tmp/mydataframe.tsv"
uCSV.write(filename, tbl; delim='\t', header=String.(names(tbl)))
```

And here's the error:
```julia
julia> uCSV.write(filename, tbl; delim='\t', header=String.(names(tbl)))
ERROR: TypeError: in #write, in typeassert, expected Union{Missing, Array{T,1} where T}, got DataFrames.DataFrameColumns{DataFrame,AbstractArray{T,1} where T}
Stacktrace:
 [1] (::getfield(uCSV, Symbol("#kw##write")))(::NamedTuple{(:header, :data, :delim),Tuple{Array{String,1},DataFrames.DataFrameColumns{DataFrame,AbstractArray{T,1} where T},Char}}, ::typeof(uCSV.write), ::String) at ./none:0
 [2] #write#16(::Base.Iterators.Pairs{Symbol,Char,Tuple{Symbol},NamedTuple{(:delim,),Tuple{Char}}}, ::Function, ::String, ::DataFrame) at /home/jock/.julia/packages/uCSV/hdtg0/src/write.jl:103
 [3] (::getfield(uCSV, Symbol("#kw##write")))(::NamedTuple{(:delim,),Tuple{Char}}, ::typeof(uCSV.write), ::String, ::DataFrame) at ./none:0
 [4] top-level scope at none:0
```

Not sure what's happening here. Is this an easy fix?

**Comment by cjprybol** [comment]
Thanks for filing an issue and sorry about the error. It looks like `DataFrames.columns()`, which is being used [here](https://github.com/cjprybol/uCSV.jl/blob/master/src/write.jl#L103), now returns a different type than it used to. It should be an easy fix, I think [this line](https://github.com/cjprybol/uCSV.jl/blob/master/src/write.jl#L46) needs to be changed from 
```
data::Union{Vector{<:Any}, Missing}=missing,
``` 
to 
```
data::Union{AbstractVector{<:Any}, Missing}=missing,
```
to accommodate the `DataFrames.DataFrameColumns{DataFrame,AbstractArray{T,1} where T}` type that is now being returned by `DataFrames.columns()`. As a quick work around, you can call the main write function directly with something like this
```julia
uCSV.write(filename, data=[c for c in DataFrames.columns(tbl)], delim='\t', header=String.(names(tbl)))
```
