### ISSUE TITLE
Failed to parse Fannie Mae data

### ISSUE THREAD

**Issue by xiaodaigh** [cjprybol/uCSV.jl#5]
[The Fannie Mae data](http://fanniemae.com/portal/funding-the-market/data/loan-performance-data.html)

I think uCSV can parse the example data but you need to log in and download the actual Performance data and you will see that it can't parse it. I tried the same in R's data.table and it was able to parse the data at speed.

I can't figure out how to make an MWE as I was not able to trace the exact line that cause the error and I think the best way to test it is to download the data and try.

**Comment by cjprybol** [comment]
Thanks for the report, I'll see if I can track down the issue. Were you working with a specific year or the entire dataset?

**Comment by xiaodaigh** [comment]
I couldn't read any of the "performance" files. I tried the largest file
and the smallest file.

**Comment by cjprybol** [comment]
I added an example for parsing one of the performance files as a test https://github.com/cjprybol/uCSV.jl/blob/master/test/runtests.jl#L1632. You may need to adjust that example to correctly read files from other years/quarters, but I hope it's a helpful place to start

**Comment by xiaodaigh** [comment]
I can load the data now with

```julia
# using Missings # for < Julia v0.7
using uCSV

const types = [
    String,                    Union{String, Missing},     Union{String, Missing},     Union{Float64, Missing},    Union{Float64, Missing},
    Union{Float64, Missing},    Union{Float64, Missing},    Union{Float64, Missing},    Union{String, Missing},     Union{String, Missing},
    Union{String, Missing},     Union{String, Missing},     Union{String, Missing},     Union{String, Missing},     Union{String, Missing},
    Union{String, Missing},     Union{String, Missing},     Union{Float64, Missing},    Union{Float64, Missing},    Union{Float64, Missing},
    Union{Float64, Missing},    Union{Float64, Missing},    Union{Float64, Missing},    Union{Float64, Missing},    Union{Float64, Missing},
    Union{Float64, Missing},    Union{Float64, Missing},    Union{Float64, Missing},    Union{String, Missing},     Union{Float64, Missing},
    Union{String, Missing}]

@time a = uCSV.read("d:/data/fannie_mae/Performance_All/Performance_2000Q1.txt", delim='|',
header=false,
types = types,
encodings = Dict("" => missing))
```

**Comment by cjprybol** [comment]
Glad to hear that you found a solution!
