### ISSUE TITLE
Package doesn't install properly using Pkg3, DataFrames not in dependencies?

### ISSUE THREAD

**Issue by moustachio-belvedere** [cjprybol/uCSV.jl#6]
This applies to Julia 0.7. Apologies if this is redundant as I'm not sure what the long term plans are for the package but when I tried installing uCSV it worked OK, but when I tried to run it gave error:

```
ERROR: LoadError: ArgumentError: Package uCSV does not have DataFrames in its dependencies:
- If you have uCSV checked out for development and have
  added DataFrames as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with uCSV
```
I think this because although we added DataFrames to the REQUIRE, that method of listing package dependencies is now deprecated. I'm still learning about Pkg3 so not able to put in PR right now for the Pkg3 toml dependencies file but thought I should post an issue here.

**Comment by cjprybol** [comment]
Thanks for reporting this. I've added the toml files for Pkg3 compatibility and that seems to have resolved the error. I'm learning the ins and outs of Pkg3 as well so there might still be some issues. Please let me know if you get the same error after updating and checking out the current master branch

**Comment by cjprybol** [comment]
I tagged a new release that is building and functioning correctly for Julia 0.7 on appveyor and travis. I think it should be ready to use on Julia 1.0 as well. Feel free to open a new issue if you run into more problems
